### ISSUE TITLE
the result of ios aesEncrypt is not the same with android

### ISSUE THREAD

**Issue by sfnt** [tomkrus007/cordova-plugin-security#2]
I set IV to '7LakyCTh2s928V4k'
in android 

aesEncrypt('1234567890','57a92aaa6577264675a7e8d469ef4851',function(text){console.log(text);},function(text){console.log(text);})

the result is 'ny/XTz9UQZoouC7lfz+Rmg=='
but in ios the result is '1UEPt4sClpvhjTjcpZEi5w=='

安卓和苹果加密不一致？……

**Comment by tomkrus007** [comment]
keep the same IV in Android & iOS。

**Comment by sfnt** [comment]
I find out why it was not the same .

the length of key must not longer then 16.

I use a 32 length key, and ios set the key to ''

can you fix this?

**Comment by tomkrus007** [comment]
only 16 bit working
